import type { Theme } from './types/theme';

function headingDefaults(
  fontSize: string,
  overrides?: Partial<Theme['elements']['h1']>,
): Theme['elements']['h1'] {
  return {
    fontFamily: 'inherit',
    fontSize,
    fontWeight: '700',
    color: '#111827',
    alignment: 'left',
    marginTop: '24px',
    marginBottom: '12px',
    borderBottom: 'none',
    paddingBottom: '0',
    pageBreakBefore: false,
    textTransform: 'none',
    headingStyle: 'plain',
    ...overrides,
  };
}

export const defaultTheme: Theme = {
  name: 'Standard',
  version: '1.0',
  page: {
    size: 'letter',
    orientation: 'portrait',
    margins: { top: '1in', right: '1in', bottom: '1in', left: '1in' },
    background: '#ffffff',
    maxWidth: '800px',
  },
  typography: {
    baseFontFamily: 'Inter, system-ui, sans-serif',
    baseFontSize: '12pt',
    baseLineHeight: '1.6',
    baseColor: '#1a1a1a',
  },
  elements: {
    h1: headingDefaults('24pt', {
      marginTop: '0',
      borderBottom: '2px solid #2563eb',
      paddingBottom: '8px',
      headingStyle: 'underline',
      headingBorderColor: '#2563eb',
    }),
    h2: headingDefaults('20pt'),
    h3: headingDefaults('16pt'),
    h4: headingDefaults('14pt'),
    h5: headingDefaults('13pt'),
    h6: headingDefaults('12pt'),
    paragraph: {
      fontSize: '12pt',
      lineHeight: '1.6',
      marginBottom: '16px',
      firstLineIndent: '0',
      color: '#374151',
      textAlign: 'left',
    },
    blockquote: {
      borderLeft: '4px solid #2563eb',
      background: '#eff6ff',
      padding: '16px',
      fontStyle: 'italic',
      marginBottom: '16px',
    },
    code_inline: {
      fontFamily: "'JetBrains Mono', 'Fira Code', monospace",
      fontSize: '10pt',
      background: '#f3f4f6',
      padding: '2px 4px',
      borderRadius: '3px',
      color: '#dc2626',
    },
    code_block: {
      fontFamily: "'JetBrains Mono', 'Fira Code', monospace",
      fontSize: '10pt',
      background: '#1e293b',
      color: '#e2e8f0',
      padding: '24px',
      borderRadius: '8px',
      lineNumbers: false,
    },
    image: {
      maxWidth: '100%',
      alignment: 'center',
      borderRadius: '0px',
      shadow: 'none',
      captionFontSize: '10pt',
      captionColor: '#6b7280',
      captionAlign: 'center',
      captionPosition: 'below',
      captionFontStyle: 'normal',
    },
    table: {
      borderStyle: 'bordered',
      headerBackground: '#f9fafb',
      headerFontWeight: '600',
      cellPadding: '12px',
      fontSize: '10pt',
    },
    link: {
      color: '#2563eb',
      underline: true,
      hoverColor: '#1d4ed8',
    },
    hr: {
      style: 'solid',
      color: '#e5e7eb',
      width: '100%',
      thickness: '1px',
      margin: '32px 0',
    },
    list_ordered: {
      style: 'decimal',
      indentPerLevel: '24px',
      itemSpacing: '4px',
    },
    list_unordered: {
      style: 'disc',
      customBullet: '\u2192',
      indentPerLevel: '24px',
      itemSpacing: '4px',
    },
    mermaid: {
      background: '#f8fafc',
      fontSize: '14px',
      fontFamily: 'system-ui, sans-serif',
      lineColor: '#94a3b8',
      nodeColor: '#3b82f6',
      secondaryColor: '#dbeafe',
      primaryBorderColor: '#3b82f6',
      textColor: '#1e293b',
      edgeLabelBackground: '#ffffff',
      noteBkgColor: '#fff3cd',
      noteTextColor: '#664d03',
      borderRadius: '8px',
    },
  },
  document: {
    tableOfContents: {
      enabled: false,
      depth: 3,
      title: 'Table of Contents',
      style: 'simple',
    },
    pageNumbers: {
      enabled: false,
      position: 'bottom-center',
      format: '1',
      startFrom: 1,
    },
    header: {
      enabled: false,
      content: '',
      fontSize: '9pt',
      color: '#9ca3af',
    },
    footer: {
      enabled: false,
      content: '',
      fontSize: '9pt',
      color: '#9ca3af',
    },
    coverPage: {
      enabled: false,
      layout: 'centered',
    },
  },
};
